# Generated by Django 5.0 on 2023-12-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ias_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Alumno',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
